model: mlae.model.MaximumLikelihoodAutoencoder

data_set:
  name: sine
  root: .

noise: 0.1  # This is varied

lr_scheduler: "onecyclelr"

loss_weights:
  nll: 1
  noisy_reconstruction: 10  # This is varied in the paper

batch_size: 128
optimizer:
  name: adam
  lr: 0.001
max_epochs: 50

accelerator: "cpu"
num_workers: 0
