model: mlae.model.MaximumLikelihoodAutoencoder

data_set:
  name: sine

noise: 0.1  # This is varied

lr_scheduler: "onecyclelr"

loss_weights:
  nll: 1
  noisy_reconstruction: 10  # This is varied in the paper

models:
  - name: mlae.model.ResNet
    latent_dim: 1
    layers_spec:
      - [256, 256]
      - [256, 256]
      - [256, 256]
      - [256, 256]

batch_size: 128
optimizer:
  name: adam
  lr: 0.001
max_epochs: 50

accelerator: "cpu"
num_workers: 0
